# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Esteira CI/CD

on:
  push:
    branches:
      - dev
      - hml
      - prd

jobs:
  esteira-devops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # -------------------------
        # TESTES
        # -------------------------
      - name: Run unit tests
        run: |
          pip install -r src/requirements.txt
          pytest || true

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #     SONAR_SCANNER_OPTS: 
      #       -Dsonar.ws.timeout=60 
      #       -Dsonar.web.http.header.ngrok-skip-browser-warning=true

      # - name: SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # - name: Build image
      #   run: |
      #     docker build -t amatildes/fakeshop:${{ github.run_number }} -f src/Dockerfile src

      # - name: Trivy image scan
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: amatildes/fakeshop:${{ github.run_number }}
      #     severity: CRITICAL,HIGH
      #     exit-code: 1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build image
        run: |
            docker build -t amatildes/fakeshop:${{ github.run_number }} -f src/Dockerfile src
      - name: Push image
        run: |
          docker push amatildes/fakeshop:${{ github.run_number }}

      - name: Clone GitOps repo
        run: |
          git clone https://${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/adrianomatildes/devops-config/_git/devops-config
      
      - name: Commit and push change GitOps repo
        run: |
          cd devops-config

          BRANCH=${GITHUB_REF#refs/heads/}
          case "$BRANCH" in
            dev)
              ENV=dev
              ;;
            hml)
              ENV=hml
              ;;
            prd)
              ENV=prd
              ;;
            *)
              echo "Branch $BRANCH not allowed for deployment"
              exit 1
              ;;
          esac

          git checkout $ENV

          sed -i "s|image:.*|image: amatildes/fakeshop:${{ github.run_number }}|" apps/fake-shop/overlays/$ENV/image-patch.yaml
          


          git config user.email "ci@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "fake-shop: update image to ${{ github.run_number }} ($ENV)"
          git push